export const customers = [
  {
    customerid: 1,
    firstname: 'JOHN',
    lastname: 'DOE',
    street_address: '4356 SARATOGA AVE',
    city: 'SAN JOSE',
    state: 'CALIFORNIA',
    zip: '94534-0567',
    agegroupid: 1,
    income_rangeid: 1,
    marital_status: 'U',
    gender: 'M',
    ethnicgroupid: 1
  },
  {
    customerid: 2,
    firstname: 'MARIA',
    lastname: 'SANCHEZ',
    street_address: '81 RED POST CRESCENT',
    city: 'FAIRPORT',
    state: 'NEW YORK',
    zip: '14450-0453',
    agegroupid: 3,
    income_rangeid: 4,
    marital_status: 'M',
    gender: 'F',
    ethnicgroupid: 3
  },
  {
    customerid: 3,
    firstname: 'YUSUF',
    lastname: 'ALI',
    street_address: '720 MARYLAND AVE',
    city: 'ST. LOUIS',
    state: 'MISSOURI',
    zip: '63105-0314',
    agegroupid: 4,
    income_rangeid: 4,
    marital_status: 'M',
    gender: 'M',
    ethnicgroupid: 5
  },
  {
    customerid: 4,
    firstname: 'HARI',
    lastname: 'SINGH',
    street_address: '7603 STOWELL RD',
    city: 'SANTA MARIA',
    state: 'CALIFORNIA',
    zip: '95509-0897',
    agegroupid: 2,
    income_rangeid: 5,
    marital_status: 'U',
    gender: 'M',
    ethnicgroupid: 5
  },
  {
    customerid: 5,
    firstname: 'ALAN',
    lastname: 'WILLIAMS',
    street_address: '45 SHATTUCK AVE',
    city: 'BERKELEY',
    state: 'CALIFORNIA',
    zip: '94704-0824',
    agegroupid: 5,
    income_rangeid: 6,
    marital_status: 'M',
    gender: 'M',
    ethnicgroupid: 2
  },
  {
    customerid: 6,
    firstname: 'JOHN',
    lastname: 'MYERS',
    street_address: '4358 SARATOGA AVE',
    city: 'SAN JOSE',
    state: 'CALIFORNIA',
    zip: '94534-0567',
    agegroupid: 2,
    income_rangeid: 5,
    marital_status: 'U',
    gender: 'M',
    ethnicgroupid: 2
  },
  {
    customerid: 7,
    firstname: 'VICTORIA',
    lastname: 'RODRIGUEZ',
    street_address: '7601 STOWELL RD',
    city: 'SANTA MARIA',
    state: 'CALIFORNIA',
    zip: '95509-0897',
    agegroupid: 4,
    income_rangeid: 4,
    marital_status: 'M',
    gender: 'F',
    ethnicgroupid: 3
  },
  {
    customerid: 8,
    firstname: 'MIKE',
    lastname: 'WILLIAMS',
    street_address: '45 SHATTUCK AVE',
    city: 'BERKELEY',
    state: 'CALIFORNIA',
    zip: '94704-0824',
    agegroupid: 2,
    income_rangeid: 4,
    marital_status: 'M',
    gender: 'M',
    ethnicgroupid: 2
  },
  {
    customerid: 9,
    firstname: 'WILLIAM',
    lastname: 'RAY',
    street_address: '728 MARYLAND AVE',
    city: 'ST. LOUIS',
    state: 'MISSOURI',
    zip: '63105-0314',
    agegroupid: 3,
    income_rangeid: 5,
    marital_status: 'M',
    gender: 'M',
    ethnicgroupid: 1
  },
  {
    customerid: 10,
    firstname: 'IAN',
    lastname: 'WILLIAMS',
    street_address: '45 SHATTUCK AVE',
    city: 'BERKELEY',
    state: 'CALIFORNIA',
    zip: '94704-0824',
    agegroupid: 3,
    income_rangeid: 5,
    marital_status: 'M',
    gender: 'M',
    ethnicgroupid: 2
  },
  {
    customerid: 11,
    firstname: 'JAVIER',
    lastname: 'LEGAZPI',
    street_address: 'Santa Hortensia 26-28',
    city: 'BERKELEY',
    state: 'CALIFORNIA',
    zip: '94703-0824',
    agegroupid: 2,
    income_rangeid: 5,
    marital_status: 'M',
    gender: 'M',
    ethnicgroupid: 2
  },
  {
    customerid: 12,
    firstname: 'CARLOS',
    lastname: 'SIERRA',
    street_address: 'LA CALLE DEL PIRINEO',
    city: 'BERKLEY',
    state: 'CALIFORNIA',
    zip: '94703-0824',
    agegroupid: 2,
    income_rangeid: 5,
    marital_status: 'U',
    gender: 'M',
    ethnicgroupid: 2
  }
];
